### ISSUE TITLE
Is there a good way of getting the from address from a received mail?

### ISSUE THREAD

**Issue by Carpela** [jhk753/gmail-ruby-api#13]
Can get from in the gmail syntax i.e. "Bob Smith <bob@smith.com>"
Is there a way of getting just the address as per

    mail.to
    "Bob Smith <bob@smith.com>"
    mail.delivered_to
    "bob@smith.com"
    mail.from
    "John Smith <john@smith.com>"
    mail.?????
    "john@smith.com"

**Comment by jhk753** [comment]
Unfortunately the Gmail API doesn't parse headers way more than what Google gives us. 

If you want to add extra methods to Message Object. I feel that this gem should keep on basic parsing. Parsing mail.from and getting just the name of just the email is something that you can do very easily on your end.

For example:
mail.from[/<(.*?)>/m, 1]
will return "john@smith.com" in your example
