### ISSUE TITLE
"Cannot load such file" error with Rails 4.2 on Heroku

### ISSUE THREAD

**Issue by knice** [jhk753/gmail-ruby-api#5]
I have the following in the Gemfile of my rails app:  
`gem 'gmail-api-ruby', :require => 'Gmail'`

It works fine in development, but when I push to Heroku, I get the following error:
` LoadError: cannot load such file -- Gmail`

I've tried requiring the gem directly in my controller as well. I'm not sure if it is an issue with the gem, because this is the only gem in my Gemfile using `:require` to load the gem as a different name. But I thought I'd ask just in case.

- Ruby: 2.2.0
- Bundler: 1.8.5
- Rails: 4.2.0

**Comment by knice** [comment]
I discovered the `:require` bit in the Gemfile is case sensitive. I changed `'Gmail'` to `'gmail'`, rebundled, and everything worked.

**Comment by Carpela** [comment]
This problem still occurs with heroku. I'd suggest updating the readme to require 'gmail' rather than Gmail, as this avoids the issue.
