### ISSUE TITLE
noMethodError with sending Multipart message generated by Mail gem

### ISSUE THREAD

**Issue by hchang239** [jhk753/gmail-ruby-api#6]
Hi,
First of all, thank you so much for writing such a wonderful gem!!
I have an issue with sending an email with Multipart message that I generate using Mail gem.
I follow what you suggest on documentation; however, when I try to call deliver method on
gmail (e.g. gmail = Gmail::Message.new(raw: raw) where raw is encoded string of Mail object),
I got "*** NoMethodError Exception: undefined method `tr' for nil:NilClass" error.
Please let me know if you want to look at my source code!

**Comment by jhk753** [comment]
Sorry for the late reply, did you find a solution to your issue ?

Using raw code is tricky as it should be encoded perfectly. Is the error coming from my code ? In this case what is the line and file ?
