### ISSUE TITLE
Can this be adapted to authenticate with a Service Account?

### ISSUE THREAD

**Issue by Carpela** [jhk753/gmail-ruby-api#9]
Can have a go at adding the code, though a bit of a newbie at that...

**Comment by Carpela** [comment]
I've made an attempt here. 
[carpela/gmail-ruby-api](https://github.com/Carpela/gmail-ruby-api)

**Comment by jhk753** [comment]
If it works, you can do a pull request and I'll see if we can merge it to the gem

**Comment by Carpela** [comment]
I've got it working. Not quite sure how to create a pull request on a repo I don't have access to.

**Comment by Carpela** [comment]
Sorry, I think you'll need to wipe out the changes to the gemspec as those are obviously not appropriate for your repo.

**Comment by jhk753** [comment]
Yes I'll change this and resubmit the gem
